package com.support.common.constants;

public enum ErrorCategoryEnum {
	MISSING_DOC_BARCODE,
	MISSING_SHIPPING_BARCODE,
	DOC_BARCODE_ALREADY_USED,
	CANT_REUSE_COVERSHEET,
	FILE_PATH_NOT_FOUND,
	DOC_BARCODE_NA,
	NCM_ERROR,
	FILE_UPLOAD_ERROR,
	DOC_GENERATION_ID_FAILURE,
	FINAL_FILE_SENT_FAILURE,
	GENERAL_ERROR,
	NWF_PROCESS_GENERATION_FAILURE,
	NWF_WRONG_PROPERTY,
	REIMAGE_CHECKOUT_ERROR,
	REIMAGE_CHECKIN_ERROR,
	DB_ERROR,
	SHIPMENT_NOT_FOUND,
	FILE_TO_FOLDER_MV_ERR,
	FOLDER_TO_FOLDER_MV_ERR

}
